# Generated by Django 4.0.4 on 2022-05-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_currency_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='free',
            new_name='available',
        ),
    ]
