# Generated by Django 4.0.4 on 2022-05-04 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_producttimetable_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttimetable',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), blank=True, null=True, size=None),
        ),
    ]
