# Generated by Django 4.0.4 on 2022-05-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_producttimetable_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttimetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='producttimetable',
            name='start_time',
        ),
    ]
