# Generated by Django 4.0.4 on 2022-05-04 17:24

from django.db import migrations, models
import django.utils.timezone
import shop.models.timetable


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_producttimetable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttimetable',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producttimetable',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
