# Generated by Django 4.0.4 on 2022-05-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_producttimetable_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttime',
            old_name='tentor',
            new_name='tenant',
        ),
    ]
