# Generated by Django 4.0.4 on 2022-05-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
