# Generated by Django 4.0.4 on 2022-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0003_review_bookmarks_count_review_comments_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
